// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqLCHdeGnqiSqpk-QUV8RbE-L4tdqVyDM',
    appId: '1:502291973539:web:5ebe948ed4f48d7c610616',
    messagingSenderId: '502291973539',
    projectId: 'fapp3-a05ac',
    authDomain: 'fapp3-a05ac.firebaseapp.com',
    storageBucket: 'fapp3-a05ac.appspot.com',
    measurementId: 'G-LG9K1SN1PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpvK0WQH1uTKq9_S24p57D12VR2pg_mdg',
    appId: '1:502291973539:android:ebb58db5109c69d9610616',
    messagingSenderId: '502291973539',
    projectId: 'fapp3-a05ac',
    storageBucket: 'fapp3-a05ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC2qZZGeJCuY36ySC8zWizIAM07Icdw8A',
    appId: '1:502291973539:ios:8888c67d0005f1d0610616',
    messagingSenderId: '502291973539',
    projectId: 'fapp3-a05ac',
    storageBucket: 'fapp3-a05ac.appspot.com',
    iosBundleId: 'com.example.fapp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC2qZZGeJCuY36ySC8zWizIAM07Icdw8A',
    appId: '1:502291973539:ios:3f9b7ddf638af24d610616',
    messagingSenderId: '502291973539',
    projectId: 'fapp3-a05ac',
    storageBucket: 'fapp3-a05ac.appspot.com',
    iosBundleId: 'com.example.fapp3.RunnerTests',
  );
}
